name: CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --output-path=./dist/out

    - name: Build Docker image
      run: docker build -t ${{ github.repository }} .

    - name: Push Docker image to Docker Hub (replace with your Docker registry)
      run: |
        echo ${{ secrets.DOCKER_USERNAME }} echo ${{ secrets.DOCKER_PASSWORD }}
        docker tag ${{ github.repository }} ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}
        docker push ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH to server and deploy Docker container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        script: |
          docker stop angular-app || true
          docker rm angular-app || true
          docker pull ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}
          docker run -d -p 80:80 --name angular-app ${{ secrets.DOCKER_REGISTRY_URL }}/${{ github.repository }}
