name: CI/CD Pipeline

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build --prod

      - name: Deploy to Nginx server
        uses: easingthemes/ssh-deploy@v2.2.3
        with:
          server: ${{ secrets.SSH_PRIVATE_KEY }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_HOST }}
          local_path: ./dist/my-app/
          server_path: /var/www/html/
          
      - name: Restart Nginx
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl restart nginx"
